name: Lint YAML

on: [pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run yamllint with reviewdog
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          yamllint_flags: |
            -d {rules:{line-length:{max:80}}} .
